# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Test Frontend Feature Branch of Url Shortener (if commit matches "run-ft-branch-cicd")

on:
  push:
    branches:
      - 'FT-*'

permissions:
  contents: read
  packages: write

jobs:
  extract-commit-message:
    runs-on: ubuntu-latest
    outputs:
      matched: ${{ steps.check.outputs.matched }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          msg=$(git log -1 --pretty=%B)
          echo "Commit message: $msg"
          if [[ "$msg" == *"run-ft-branch-cicd"* ]]; then
            echo "matched=true" >> $GITHUB_OUTPUT
          else
            echo "matched=false" >> $GITHUB_OUTPUT
          fi

  branch-cicd-pipeline:
    needs: extract-commit-message
    if: needs.extract-commit-message.outputs.matched == 'true'
    runs-on: ubuntu-latest

    outputs:
      branch_name: ${{ steps.set_branch.outputs.branch_name }}

    strategy:
      matrix:
        node-version: [22.21.0]

    steps:
    - name: â¬‡ï¸ Checkout code
      uses: actions/checkout@v3

    - name: ğŸŸ¢ Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: ğŸ“¦ Install frontend dependencies
      run: npm ci

    - name: ğŸ§ª Run frontend tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: ğŸ§¹ Lint frontend
      run: npm run lint

    - name: ğŸ—ï¸ Build frontend
      run: npm run build -- --configuration=production

    - name: Get sanitised branch name
      id: set_branch
      run: |
        branch_name="${GITHUB_REF#refs/heads/}"

  deploy-ui:
    needs: branch-cicd-pipeline
    uses: ./.github/workflows/deploy-ui-as-container.yml
    with:
      image_name: url-shortener-ui
      image_tag: "${{ needs.branch-cicd-pipeline.outputs.branch_name }}-testing"
