# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Test Release Branch of Url Shortener

on:
  push:
    branches:
      - 'Release*'  # Matches any branch starting with 'Release'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.21.0]

    steps:
    - name: â¬‡ï¸ Checkout code
      uses: actions/checkout@v3

    - name: ğŸŸ¢ Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: ğŸ“¦ Install frontend dependencies
      run: npm ci

    - name: ğŸ§ª Run frontend tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless

    - name: ğŸ§¹ Lint frontend
      run: npm run lint
      continue-on-error: true

    - name: ğŸ—ï¸ Build frontend
      run: npm run build -- --configuration=production

